### ISSUE TITLE
How to get the address components of a selected suggestion

### ISSUE THREAD

**Issue by GobbaFish** [Giners/mui-places-autocomplete#43] opened 2018-11-14 06:21 UTC
In your pic in the readme, it appears that you are rendering the address components of the suggested place
https://camo.githubusercontent.com/c3209e2f2c7634ac62b42181ae810db36bfab2e8/687474703a2f2f672e7265636f726469742e636f2f527864343964776265762e676966

Can I ask how you did this as the selected suggestion isn't broken up into its components

**Comment by Giners** [comment] 2019-02-22 18:24
Hi @GobbaFish,

Sorry I haven't gotten back to you sooner. Check out issue #44. The author of the issue is trying to do the same things as you are and I have provided guidance on how to do this. Let me know if this helps.

I'm going to close this issue since its a dupe of #44 and I started to respond in that thread. If you need more help please follow up with me in that thread and I would be happy to assist.

**Closed as completed by Giners** 2019-02-22 18:24 UTC
