### ISSUE TITLE
Fix issues arising with material-ui v1

### ISSUE THREAD

**Issue by charlax** [Giners/mui-places-autocomplete#37] opened 2018-05-18 15:51 UTC
material-ui was released [a day ago](https://medium.com/material-ui/material-ui-v1-is-out-e73ce13463eb) and broke a couple stuff, including import paths for menu.

You can checkout the breaking changes here: https://github.com/mui-org/material-ui/releases

I'll try to put together a PR to fix things.

**Comment by Giners** [comment] 2018-05-21 12:39
Hey @charlax,

Thanks for bringing this to my attention. I really appreciate your continued usage of `<MUIPlacesAutocomplete>`. Life has been so busy lately that I haven't had much time to continue to iterate and improve `<MUIPlacesAutocomplete>`.

Bug #38 was also filed for the same reasons so I am going to close this bug as a duplicate of that. I'll try to resolve the issues and close out bug #38 ASAP.

**Closed as completed by Giners** 2018-05-21 12:39 UTC
Labels: bug, duplicate
